name: modbus_client
description: This is the base Modbus Client package sending requests to a remote device (i.e. Modbus Server) via Serial (ASCII and RTU) or TCP/IP connection.
version: 1.4.1
repository: https://github.com/cabbi/modbus_client

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.17.1
  logging: ^1.2.0
  meta: ^1.15.0
  synchronized: ^3.1.0+1

dev_dependencies:
  lints: ^5.1.0
  test: ^1.21.0
