name: modbus_client_tcp
description: This is the Modbus Client package sending requests to a remote device via TCP/IP connection.
version: 1.2.1+2
repository: https://github.com/cabbi/modbus_client_tcp

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.17.1
  logging: ^1.2.0
  meta: ^1.16.0
  synchronized: ^3.1.0+1
  modbus_client: ^1.4.1

dev_dependencies:
  lints: ^5.1.0
  test: ^1.21.0

